server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# TODO mysql - table charset utf8로 설정해야 함
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.114.118:3306/OSS?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      location: ${java.io.tmpdir}
      max-file-size: 500MB
      max-request-size: 500MB

logging.level:
  org.hibernate:
    SQL: debug
    type: trace