server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# TODO mysql - table charset utf8로 설정해야 함
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(KaaEO/pTDmbAgCULySW72sqO73uTcZQ+lbUB3DAHtNrVowEdDcnAoUMKQrWOVAfhJ90B0NxxPoqe8oXqiRsSZQgMXmHiKS5H/Mx3DdpX8lYFNmCBkZ6gWwFJwUzxtVkr8HLgkZlPK5U=)
    username: ENC(XNSDVrY4hqaW6/cyKwbedg==)
    password: ENC(ma+pnruxyVM4mAPYyBs/FA==)

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      location: ${java.io.tmpdir}
      max-file-size: 500MB
      max-request-size: 500MB

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging.level:
  org.hibernate:
    SQL: debug
    type: trace