name: auto build for artifact and auto deploy
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.

      - name: allow mvnw permission
        run: chmod +x gradlew
        working-directory: server/

      - name: backend dependency install
        run: ./gradlew clean build
        working-directory: server/

      - name: backend build
        run: ./gradlew test
        working-directory: server/

      - name: frontend dependy install
        run: npm install
        working-directory: client/

      - name: frontend build
        run: npm run build
        working-directory: client/

      - name: Archive backend build result
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: server/build/libs/*.jar

      - name: backend build file upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          source: "server/build/libs/*.jar"
          target: "/home/oss"

      - name: run backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: sh /home/oss/auto-run.sh