name: auto build for artifact and auto deploy test1
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.

      - name: allow gradle permission
        run: chmod +x gradlew
        working-directory: server/

      - name: backend dependency install
        run: ./gradlew clean build
        working-directory: server/

      - name: backend test
        run: ./gradlew test
        working-directory: server/

      - name: Archive backend build result
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: server/build/libs/*.jar

      - name: backend build file upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "server/build/libs/*.jar"
          target: "/home/oss"
